CPU: CPU.v IF.v InstructionRAM.v ID.v EX.v ALU.v MEM.v MainMemory.v WB.v CPU_test.v 
	iverilog -o CPU CPU.v IF.v InstructionRAM.v ID.v EX.v ALU.v MEM.v MainMemory.v WB.v CPU_test.v
	
clean:
	rm -rf CPU

execute:
	./CPU